# Generated by Django 5.0.14 on 2026-08-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("zelle", "Zelle"),
                    ("chime", "Chime"),
                    ("apple_pay", "Apple Pay"),
                    ("cash_app", "Cash App"),
                    ("e_transfer", "E-Transfer"),
                    ("bank_transfer", "Bank Transfer"),
                    ("payid", "PayID"),
                    ("crypto", "Crypto"),
                ],
                max_length=20,
            ),
        ),
    ]
