# Generated by Django 5.0.14 on 2026-08-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
