// Transcribed directly from the supplier's wholesale price sheet (3 screenshots).
// Excluded line items (illegal to sell/distribute without a prescription or
// specific authorization): Botulinum toxin, HCG, Insulin, EPO, Survodutide,
// Mazdutide. Where the sheet listed the same item twice at different prices
// (CJC-1295 With DAC), the lower price was kept.
//
// `slug` links a row to its live product page when the exact size/variant is
// sold in our catalog today; `null` means the item (or that specific size) is
// on the supplier sheet but not yet a product on the site.
export const WHOLESALE_PRICE_SHEET = [
  { catNo: "SM2", name: "Samaglutide (Semaglutide)", spec: "2 mg/vial · 10vial/kit", price: 25, slug: "semaglutide" },
  { catNo: "SM5", name: "Samaglutide (Semaglutide)", spec: "5 mg/vial · 10vial/kit", price: 29, slug: "semaglutide" },
  { catNo: "SM10", name: "Samaglutide (Semaglutide)", spec: "10 mg/vial · 10vial/kit", price: 43, slug: "semaglutide" },
  { catNo: "SM15", name: "Samaglutide (Semaglutide)", spec: "15 mg/vial · 10vial/kit", price: 55, slug: "semaglutide" },
  { catNo: "SM20", name: "Samaglutide (Semaglutide)", spec: "20 mg/vial · 10vial/kit", price: 66, slug: "semaglutide" },
  { catNo: "SM30", name: "Samaglutide (Semaglutide)", spec: "30 mg/vial · 10vial/kit", price: 84, slug: "semaglutide" },
  { catNo: "TR5", name: "Tirzepatide", spec: "5 mg/vial · 10vial/kit", price: 31, slug: "tirzepatide" },
  { catNo: "TR10", name: "Tirzepatide", spec: "10 mg/vial · 10vial/kit", price: 45, slug: "tirzepatide" },
  { catNo: "TR15", name: "Tirzepatide", spec: "15 mg/vial · 10vial/kit", price: 61, slug: "tirzepatide" },
  { catNo: "TR20", name: "Tirzepatide", spec: "20 mg/vial · 10vial/kit", price: 70, slug: "tirzepatide" },
  { catNo: "TR30", name: "Tirzepatide", spec: "30 mg/vial · 10vial/kit", price: 90, slug: "tirzepatide" },
  { catNo: "TR40", name: "Tirzepatide", spec: "40 mg/vial · 10vial/kit", price: 109, slug: "tirzepatide" },
  { catNo: "TR50", name: "Tirzepatide", spec: "50 mg/vial · 10vial/kit", price: 133, slug: "tirzepatide" },
  { catNo: "TR60", name: "Tirzepatide", spec: "60 mg/vial · 10vial/kit", price: 158, slug: "tirzepatide" },
  { catNo: "RT5", name: "Retatrutide", spec: "5 mg/vial · 10vial/kit", price: 47, slug: "retatrutide-30mg" },
  { catNo: "RT10", name: "Retatrutide", spec: "10 mg/vial · 10vial/kit", price: 74, slug: "retatrutide-30mg" },
  { catNo: "RT15", name: "Retatrutide", spec: "15 mg/vial · 10vial/kit", price: 94, slug: "retatrutide-30mg" },
  { catNo: "RT20", name: "Retatrutide", spec: "20 mg/vial · 10vial/kit", price: 117, slug: "retatrutide-30mg" },
  { catNo: "RT30", name: "Retatrutide", spec: "30 mg/vial · 10vial/kit", price: 156, slug: "retatrutide-30mg" },
  { catNo: "BC5", name: "BPC-157", spec: "5 mg/vial · 10vial/kit", price: 38, slug: "bpc-157" },
  { catNo: "BC10", name: "BPC-157", spec: "10 mg/vial · 10vial/kit", price: 54, slug: "bpc-157" },
  { catNo: "BT5", name: "TB-500 (Thymosin β4 Acetate)", spec: "5 mg/vial · 10vial/kit", price: 67, slug: "tb-500" },
  { catNo: "BT10", name: "TB-500 (Thymosin β4 Acetate)", spec: "10 mg/vial · 10vial/kit", price: 119, slug: "tb-500" },
  { catNo: "375", name: "LL-37", spec: "10 mg/vial · 10vial/kit", price: 73, slug: "ll-37-10mg" },
  { catNo: "CU50", name: "GHK-Cu", spec: "50 mg/vial · 10vial/kit", price: 25, slug: "ghk-cu" },
  { catNo: "CU100", name: "GHK-Cu", spec: "100 mg/vial · 10vial/kit", price: 31, slug: "ghk-cu" },
  { catNo: "NJ100", name: "NAD+", spec: "100 mg/vial · 10vial/kit", price: 29, slug: "nad" },
  { catNo: "NJ500", name: "NAD+", spec: "500 mg/vial · 10vial/kit", price: 67, slug: "nad" },
  { catNo: "GTT", name: "Glutathione", spec: "1500 mg/vial · 10vial/kit", price: 63, slug: "glutathione-1500mg" },
  { catNo: "CGL5", name: "Cagrilintide", spec: "5 mg/vial · 10vial/kit", price: 94, slug: "cagri-10mg" },
  { catNo: "CGL10", name: "Cagrilintide", spec: "10 mg/vial · 10vial/kit", price: 146, slug: "cagri-10mg" },
  { catNo: "NP810", name: "Snap-8", spec: "10 mg/vial · 10vial/kit", price: 36, slug: "snap-8-10mg" },
  { catNo: "LB10", name: "Lemon Bottle", spec: "10ml/vial · 10vial/kit", price: 63, slug: "lemon-bottle-10ml" },
  { catNo: "XA5", name: "Semax", spec: "5 mg/vial · 10vial/kit", price: 31, slug: "semax-5mg" },
  { catNo: "XA10", name: "Semax", spec: "10 mg/vial · 10vial/kit", price: 46, slug: "semax-5mg" },
  { catNo: "SK5", name: "Selank", spec: "5 mg/vial · 10vial/kit", price: 31, slug: "selank-5mg" },
  { catNo: "SK10", name: "Selank", spec: "10 mg/vial · 10vial/kit", price: 50, slug: "selank-5mg" },
  { catNo: "TSM5", name: "Tesamorelin", spec: "5 mg/vial · 10vial/kit", price: 88, slug: "tesamorelin" },
  { catNo: "TSM10", name: "Tesamorelin", spec: "10 mg/vial · 10vial/kit", price: 167, slug: "tesamorelin" },
  { catNo: "CP10", name: "CJC-1295 No DAC + Ipamorelin Blend", spec: "5 mg + 5 mg/vial · 10vial/kit", price: 88, slug: "cjc-1295-no-dac-ipamorelin-blend-5mg-5mg" },
  { catNo: "LC120", name: "LC120", spec: "10 mg/vial · 10vial/kit", price: 63, slug: null },
  { catNo: "LC216", name: "Lipo-C with Vitamin B12", spec: "10 mg/vial · 10vial/kit", price: 63, slug: null },
  { catNo: "LC600", name: "L-Carnitine", spec: "10 mg/vial · 10vial/kit", price: 73, slug: null },
  { catNo: "CBL60", name: "Cerebrolysin", spec: "60 mg/vial · 6vial/kit", price: 36, slug: "cerebrolysin-60mg" },
  { catNo: "5AD", name: "AOD-9604", spec: "5 mg/vial · 10vial/kit", price: 88, slug: "aod-9604-5mg" },
  { catNo: "KPV5", name: "KPV (Lysine-Proline-Valine)", spec: "5 mg/vial · 10vial/kit", price: 40, slug: "kpv-10mg" },
  { catNo: "KPV10", name: "KPV (Lysine-Proline-Valine)", spec: "10 mg/vial · 10vial/kit", price: 50, slug: "kpv-10mg" },
  { catNo: "VIP5", name: "VIP", spec: "5 mg/vial · 10vial/kit", price: 67, slug: "vip-10mg" },
  { catNo: "VIP10", name: "VIP", spec: "10 mg/vial · 10vial/kit", price: 119, slug: "vip-10mg" },
  { catNo: "IG01", name: "IGF-1 LR3", spec: "0.1 mg/vial · 10vial/kit", price: 31, slug: "igf-1-lr3-1mg" },
  { catNo: "IG1", name: "IGF-1 LR3", spec: "1 mg/vial · 10vial/kit", price: 167, slug: "igf-1-lr3-1mg" },
  { catNo: "IP5", name: "Ipamorelin", spec: "5 mg/vial · 10vial/kit", price: 36, slug: "ipamorelin" },
  { catNo: "IP10", name: "Ipamorelin", spec: "10 mg/vial · 10vial/kit", price: 63, slug: "ipamorelin" },
  { catNo: "MS5", name: "MOTS-c", spec: "5 mg/vial · 10vial/kit", price: 54, slug: "mots-c-10mg" },
  { catNo: "MS40", name: "MOTS-c", spec: "40 mg/vial · 10vial/kit", price: 161, slug: "mots-c-10mg" },
  { catNo: "322", name: "SLU-PP-332", spec: "5 mg/vial · 10vial/kit", price: 109, slug: "slu-pp-332-research-capsules" },
  { catNo: "ET10", name: "Epithalon", spec: "10 mg/vial · 10vial/kit", price: 40, slug: "epitalon-10mg" },
  { catNo: "ET50", name: "Epithalon", spec: "50 mg/10vials · 10vial/kit", price: 115, slug: "epitalon-10mg" },
  { catNo: "P41", name: "PT-141", spec: "10 mg/vial · 10vial/kit", price: 50, slug: "pt-141-10mg" },
  { catNo: "DS5", name: "DSIP", spec: "5 mg/vial · 10vial/kit", price: 36, slug: "dsip-5mg" },
  { catNo: "DS15", name: "DSIP", spec: "15 mg/vial · 10vial/kit", price: 77, slug: "dsip-5mg" },
  { catNo: "TA5", name: "Thymosin Alpha-1", spec: "5 mg/vial · 10vial/kit", price: 73, slug: "thymosin-alpha-1-5mg" },
  { catNo: "TA10", name: "Thymosin Alpha-1", spec: "10 mg/vial · 10vial/kit", price: 136, slug: "thymosin-alpha-1-5mg" },
  { catNo: "CND5", name: "CJC-1295 No DAC", spec: "5 mg/vial · 10vial/kit", price: 73, slug: "cjc-1295-no-dac-5mg" },
  { catNo: "CND10", name: "CJC-1295 No DAC", spec: "10 mg/vial · 10vial/kit", price: 140, slug: "cjc-1295-no-dac-5mg" },
  { catNo: "CD5", name: "CJC-1295 With DAC", spec: "5 mg/vial · 10vial/kit", price: 130, slug: "cjc-1295-with-dac-5mg" },
  { catNo: "G65", name: "GHRP-6 Acetate", spec: "5 mg/vial · 10vial/kit", price: 21, slug: null },
  { catNo: "G610", name: "GHRP-6 Acetate", spec: "10 mg/vial · 10vial/kit", price: 25, slug: null },
  { catNo: "IGD", name: "IGF-DES", spec: "2 mg/vial · 10vial/kit", price: 46, slug: null },
  { catNo: "2S10", name: "SS-31 (Elamipretide)", spec: "10 mg/vial · 10vial/kit", price: 77, slug: "ss-31-elamipretide-10mg" },
  { catNo: "2S50", name: "SS-31 (Elamipretide)", spec: "50 mg/vial · 10vial/kit", price: 335, slug: null },
  { catNo: "MT1", name: "MT-1", spec: "10 mg/vial · 10vial/kit", price: 42, slug: null },
  { catNo: "ML10", name: "MT-2 (Melanotan II)", spec: "10 mg/vial · 10vial/kit", price: 38, slug: "mtii-10mg" },
  { catNo: "BBG70", name: "Glow Blend (BPC-157 + GHK-Cu + TB-500)", spec: "10 + 50 + 10 mg/vial · 10vial/kit", price: 167, slug: "glow-blend-bpc-157-tb-500-ghk-cu-10mg-10mg-50mg" },
  { catNo: "CS5", name: "Cagrilintide + Semaglutide Blend", spec: "2.5 + 2.5 mg/vial · 10vial/kit", price: 98, slug: null },
  { catNo: "CS10", name: "Cagrilintide + Semaglutide Blend", spec: "5 + 5 mg/vial · 10vial/kit", price: 172, slug: null },
  { catNo: "WA3", name: "Bacteriostatic Water", spec: "3ml/vial · 10vial/kit", price: 4, slug: null },
  { catNo: "WA10", name: "Bacteriostatic Water", spec: "10ml/vial · 10vial/kit", price: 5, slug: "bacteriostatic-water-10ml" },
  { catNo: "RA10", name: "Ara-290", spec: "10 mg/vial · 10vial/kit", price: 52, slug: "ara-290-12-mg" },
  { catNo: "TY10", name: "Thymalin", spec: "10 mg/vial · 10vial/kit", price: 50, slug: "thymalin-20mg" },
  { catNo: "H10", name: "HGH 191AA (Somatropin)", spec: "10iu · 10vial/kit", price: 48, slug: "hgh-somatropin-10iu" },
  { catNo: "H15", name: "HGH 191AA (Somatropin)", spec: "15iu · 10vial/kit", price: 65, slug: null },
  { catNo: "BB10", name: "BPC-157 + TB-500 Blend", spec: "5 + 5 mg/vial · 10vial/kit", price: 84, slug: "bpc-157-tb-500-blend" },
  { catNo: "BB20", name: "BPC-157 + TB-500 Blend", spec: "10 + 10 mg/vial · 10vial/kit", price: 172, slug: "bpc-157-tb-500-blend" },
  { catNo: "SMO5", name: "Sermorelin Acetate", spec: "5 mg/vial · 10vial/kit", price: 59, slug: "sermorelin-5mg" },
  { catNo: "SMO10", name: "Sermorelin Acetate", spec: "10 mg/vial · 10vial/kit", price: 88, slug: "sermorelin-5mg" },
  { catNo: "FN1", name: "Follistatin", spec: "1 mg/vial · 10vial/kit", price: null, slug: null },
  { catNo: "HX5", name: "Hexarelin Acetate", spec: "5 mg/vial · 10vial/kit", price: 73, slug: null },
  { catNo: "KS5", name: "Kisspeptin-10", spec: "5 mg/vial · 10vial/kit", price: 52, slug: "kisspeptin-10-10mg" },
  { catNo: "KS10", name: "Kisspeptin-10", spec: "10 mg/vial · 10vial/kit", price: 88, slug: "kisspeptin-10-10mg" },
  { catNo: "FR5", name: "HGH Fragment 176-191", spec: "5 mg/vial · 10vial/kit", price: 77, slug: null },
  { catNo: "GP", name: "GLP-1", spec: "5 mg/vial · 10vial/kit", price: 88, slug: null },
  { catNo: "5AM", name: "5-Amino-1MQ", spec: "5 mg/vial · 10vial/kit", price: 56, slug: "5-amino-1mq-50mg" },
  { catNo: "HA5", name: "Hyaluronic Acid", spec: "5 mg/vial · 1vial/kit", price: 21, slug: null },
  { catNo: "OT2", name: "Oxytocin Acetate", spec: "2 mg/vial · 10vial/kit", price: 31, slug: "oxytocin" },
  { catNo: "KLOW80", name: "KLOW Blend (GHK-Cu + TB-500 + BPC-157 + KPV)", spec: "80 mg/vial · 10vial/kit", price: 209, slug: "klow-blend-80mg" },
  { catNo: "PNC27-5", name: "PNC-27", spec: "5 mg/vial · 10vial/kit", price: 84, slug: "pnc-27-10mg" },
  { catNo: "PNC27-10", name: "PNC-27", spec: "10 mg/vial · 10vial/kit", price: 136, slug: "pnc-27-10mg" },
  { catNo: "PI5", name: "Pinealon", spec: "5 mg/vial · 10vial/kit", price: 42, slug: "pinealon-20mg" },
  { catNo: "PI10", name: "Pinealon", spec: "10 mg/vial · 10vial/kit", price: 59, slug: "pinealon-20mg" },
  { catNo: "P20", name: "Pinealon", spec: "20 mg/vial · 10vial/kit", price: 79, slug: "pinealon-20mg" },
];
