# Generated by Django 5.0.14 on 2026-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="extra_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="faq_html",
            field=models.TextField(blank=True),
        ),
    ]
